### ISSUE TITLE
android.view.InflateException: Binary XML file line #19: Error inflating class <unknown>

### ISSUE THREAD

**Issue by tevjef** [tevjef/RutgersSOC#11]
```bash
android.view.InflateException: Binary XML file line #19: Error inflating class <unknown>
	at android.view.LayoutInflater.createView(LayoutInflater.java:626)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
	at com.tevinjeffrey.rutgerssoc.ui.ChooserFragment.onCreateView(ChooserFragment.java:60)
	at android.app.Fragment.performCreateView(Fragment.java:1700)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
	at android.app.BackStackRecord.run(BackStackRecord.java:684)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1453)
	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:443)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5579)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.constructNative(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at android.view.LayoutInflater.createView(LayoutInflater.java:600)
	... 20 more
Caused by: android.content.res.Resources$NotFoundException: Resource is not a Drawable (color or path): TypedValue{t=0x1/d=0x103023f a=2 r=0x103023f}
	at android.content.res.Resources.loadDrawable(Resources.java:3412)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
	at android.view.View.<init>(View.java:3694)
	at android.view.ViewGroup.<init>(ViewGroup.java:480)
	at android.support.v7.widget.Toolbar.<init>(Toolbar.java:195)
	at android.support.v7.widget.Toolbar.<init>(Toolbar.java:191)
	... 23 more

```

**Comment by zhouwenhn** [comment]
你好，怎么解？

**Comment by zhouwenhn** [comment]
Hello, how to solve?

**Comment by tevjef** [comment]
It was fixed with this commit. https://github.com/tevjef/Rutgers-Course-Tracker/commit/219b5ee053664b92eae5f71d5f32d45865ec8915

If you have a problem with your own app, post the stacktrace and relavant code to Stackoverflow.com and post the link here. I will help.

**Comment by zhouwenhn** [comment]
ok,thinks
