### ISSUE TITLE
java.util.concurrent.CancellationException

### ISSUE THREAD

**Issue by tevjef** [tevjef/RutgersSOC#4]
```bash
java.util.concurrent.CancellationException
	at com.koushikdutta.async.future.SimpleFuture.cancelInternal(SimpleFuture.java:39)
	at com.koushikdutta.async.future.SimpleFuture.cancel(SimpleFuture.java:54)
	at com.koushikdutta.ion.Ion.cancelAll(Ion.java:320)
	at com.koushikdutta.ion.Ion.cancelAll(Ion.java:351)
	at com.tevinjeffrey.rutgerssoc.ui.TrackedSectionsFragment.onDestroyView(TrackedSectionsFragment.java:294)
	at android.app.Fragment.performDestroyView(Fragment.java:2251)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:958)
	at android.app.FragmentManagerImpl.removeFragment(FragmentManager.java:1172)
	at android.app.BackStackRecord.run(BackStackRecord.java:784)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1454)
	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:447)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5312)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)

```

**Comment by tevjef** [comment]
Non-issue. Caused when user leaves the fragment before a network request was completed.
